// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleClusterOperator) DeepCopyInto(out *ExampleClusterOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleClusterOperator.
func (in *ExampleClusterOperator) DeepCopy() *ExampleClusterOperator {
	if in == nil {
		return nil
	}
	out := new(ExampleClusterOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExampleClusterOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleClusterOperatorList) DeepCopyInto(out *ExampleClusterOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExampleClusterOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleClusterOperatorList.
func (in *ExampleClusterOperatorList) DeepCopy() *ExampleClusterOperatorList {
	if in == nil {
		return nil
	}
	out := new(ExampleClusterOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExampleClusterOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleClusterOperatorSpec) DeepCopyInto(out *ExampleClusterOperatorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleClusterOperatorSpec.
func (in *ExampleClusterOperatorSpec) DeepCopy() *ExampleClusterOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(ExampleClusterOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExampleClusterOperatorStatus) DeepCopyInto(out *ExampleClusterOperatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExampleClusterOperatorStatus.
func (in *ExampleClusterOperatorStatus) DeepCopy() *ExampleClusterOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(ExampleClusterOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
